# Generated by Django 4.1.1 on 2022-11-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_subscribe_dues_alter_subscribe_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='dues',
            field=models.CharField(choices=[('W', 'Weekly'), ('M', 'Monthly')], default='M', max_length=2),
        ),
    ]
