# Generated by Django 4.1.1 on 2022-11-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_skills_jobpost_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='type',
            field=models.CharField(choices=[('Permanent Full Time', 'F/T'), ('Permanent Part Time', 'P/T'), ('Fixed Contract', 'Cntr')], default='F/T', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='description',
            field=models.TextField(),
        ),
    ]
